#include "mainwindow.h"
#include "./ui_mainwindow.h"
#include <QFileDialog>
#include <QPixmap>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
    this->resize({1280,720});
    mode=true;


    QPixmap logo("logo.png");//logo stuff!
    ui->pic->setPixmap(logo);
    ui->pic_2->setPixmap(logo);
    ui->pic_3->setPixmap(logo);
    ui->pic_4->setPixmap(logo);//logo stuff!

    ui->stackedWidget->styleSheet();

}

MainWindow::~MainWindow()
{
    delete ui;

}



void MainWindow::on_Browse_pressed()
{
    QString filePath = QFileDialog::getOpenFileName(
        this,
        "Browse Files",
        "",  // Starting directory
        "All Files (*)"  // File filter
        );

    if (!filePath.isEmpty()) {

        qDebug() << "Selected file:" << filePath;
    }
}


void MainWindow::on_reveiw1_clicked(){
    ui->stackedWidget->setCurrentIndex(1);
}
void MainWindow::on_reveiw2_clicked(){
    ui->stackedWidget->setCurrentIndex(1);
}
void MainWindow::on_reveiw3_clicked(){
    ui->stackedWidget->setCurrentIndex(1);
}
void MainWindow::on_reveiw4_clicked(){
    ui->stackedWidget->setCurrentIndex(1);
}

void MainWindow::on_quit_clicked(){
    this->close();
}

void MainWindow::on_profile1_clicked(){
    ui->stackedWidget->setCurrentIndex(3);
}
void MainWindow::on_profile2_clicked(){
    ui->stackedWidget->setCurrentIndex(3);
}
void MainWindow::on_profile3_clicked(){
    ui->stackedWidget->setCurrentIndex(3);
}
void MainWindow::on_profile4_clicked(){
    ui->stackedWidget->setCurrentIndex(3);
}

void MainWindow::on_temp_clicked(){
    ui->stackedWidget->setCurrentIndex(0);
}

void MainWindow::on_homeButton_clicked(){
    ui->stackedWidget->setCurrentIndex(0);
}
void MainWindow::on_homeButton2_clicked(){
    ui->stackedWidget->setCurrentIndex(0);
}
void MainWindow::on_homeButton3_clicked(){
    ui->stackedWidget->setCurrentIndex(0);
}
void MainWindow::on_homeButton4_clicked(){
    ui->stackedWidget->setCurrentIndex(0);
}
void MainWindow::on_addConferenceBtn_clicked(){
    // Create popup as QMainWindow
    QMainWindow *popupWindow = new QMainWindow(this);
    popupWindow->setWindowTitle("Add Conference");
    popupWindow->setWindowModality(Qt::ApplicationModal);
    popupWindow->setMinimumSize(800, 600);
    popupWindow->setMaximumSize(800, 600);
    popupWindow->setAttribute(Qt::WA_DeleteOnClose);

    // Create a NEW instance of your UI
    Ui::MainWindow *popupUi = new Ui::MainWindow();
    popupUi->setupUi(popupWindow);

    // Set the stacked widget to the conference page
    popupUi->stackedWidget->setCurrentIndex(5);

    // Connect cancel button to close
    popupUi->cancelButton->connect(popupUi->cancelButton, &QPushButton::clicked,
                                   popupWindow, &QMainWindow::close);

    //window is destroyed
    QObject::connect(popupWindow, &QMainWindow::destroyed, [popupUi]() {
        delete popupUi;
    });

    popupWindow->show();
}


void MainWindow::toggleDarkMode(){
    mode = !mode;

    if (mode)
        ui->modeSwitch->setIcon(QIcon("icons/sun.svg"));
    else
        ui->modeSwitch->setIcon(QIcon("icons/moon.svg"));


    if(mode){
        this->setStyleSheet(
            "/* Research Publication App Stylesheet - LIGHT MODE */"
            ""
            "* {"
            "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Arial, sans-serif;"
            "}"
            ""
            "QMainWindow {"
            "    background-color: #f6f8fc;"
            "}"
            ""
            "#sidebar {"
            "    background-color: #ffffff;"
            "    border-right: 1px solid #d8e0f0;"
            "}"
            ""
            "/* For QDateEdit */"
            "QDateEdit {"
            "    background-color: #ffffff !important;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1f2937;"
            "}"
            ""
            "/* For QSpinBox / QDoubleSpinBox */"
            "QSpinBox, QDoubleSpinBox {"
            "    background-color: #ffffff !important;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1f2937;"
            "}"
            ""
            "#appTitle {"
            "    color: #1a7a7f;"
            "    font-size: 20pt;"
            "    font-weight: bold;"
            "    padding: 16px;"
            "    background-color: transparent;"
            "}"
            ""
            "/* Navigation Buttons */"
            "#homeNavButton, #myPageNavButton, #quitb {"
            "    text-align: left;"
            "    padding: 12px 16px;"
            "    border-radius: 8px;"
            "    background-color: transparent;"
            "    color: #2d3748;"
            "    font-size: 11pt;"
            "    border: none;"
            "}"
            ""
            "#homeNavButton:hover, #myPageNavButton:hover {"
            "    background-color: rgba(48, 185, 191, 0.08);"
            "}"
            ""
            "#homeNavButton:pressed, #myPageNavButton:pressed {"
            "    background-color: rgba(48, 185, 191, 0.15);"
            "}"
            ""
            "#quitb {"
            "    color: #2d3748;"
            "    margin-top: 8px;"
            "}"
            ""
            "#quitb:hover {"
            "    background-color: rgba(200, 30, 30, 0.08);"
            "    color: #c62828;"
            "}"
            ""
            "/* Top Bars */"
            "#homeTopBar, #myPageTopBar {"
            "    background-color: #f6f8fc;"
            "    padding: 16px 24px;"
            "}"
            ""
            "#homeTitle, #myPageTitle {"
            "    color: #1f2937;"
            "    font-size: 18pt;"
            "    font-weight: bold;"
            "    background-color: transparent;"
            "}"
            ""
            "/* Search Bar */"
            "QLineEdit#searchBar {"
            "    background-color: #ffffff !important;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 20px;"
            "    padding: 10px 16px;"
            "    color: #1f2937;"
            "    font-size: 10pt;"
            "}"
            ""
            "QLineEdit#searchBar:focus {"
            "    border: 2px solid #30b9bf;"
            "    background-color: #ffffff !important;"
            "}"
            ""
            "QLineEdit#searchBar:hover {"
            "    border: 1px solid #30b9bf;"
            "}"
            ""
            "/* Scroll Areas */"
            "#homeScrollArea, #myScrollArea {"
            "    background-color: #f6f8fc;"
            "    border: none;"
            "}"
            ""
            "#homeScrollArea > QWidget, #myScrollArea > QWidget {"
            "    background-color: #f6f8fc;"
            "}"
            ""
            "/* Publication Cards */"
            "#publicationCard {"
            "    background-color: #ffffff;"
            "    border-radius: 10px;"
            "    border: 1px solid #e2e8f0;"
            "}"
            ""
            "#publicationCard:hover {"
            "    border: 1px solid #30b9bf;"
            "    background-color: #f8fcff;"
            "}"
            ""
            "#cardTitle {"
            "    color: #1f2937;"
            "    font-size: 14pt;"
            "    font-weight: bold;"
            "    background-color: transparent;"
            "}"
            ""
            "#cardAuthors {"
            "    color: #4b5563;"
            "    font-size: 10pt;"
            "    background-color: transparent;"
            "}"
            ""
            "#cardDate {"
            "    color: #6b7280;"
            "    font-size: 9pt;"
            "    background-color: transparent;"
            "}"
            ""
            "/* Primary Button (Upload/Browse) */"
            "#Browse {"
            "    background-color: #30b9bf;"
            "    color: white;"
            "    border: none;"
            "    border-radius: 20px;"
            "    padding: 10px 20px;"
            "    font-weight: bold;"
            "    font-size: 10pt;"
            "}"
            ""
            "#Browse:hover {"
            "    background-color: #3dd4db;"
            "}"
            ""
            "#Browse:pressed {"
            "    background-color: #26a0a6;"
            "}"
            ""
            "/* Secondary Buttons (View, Download) */"
            "#secondaryButton {"
            "    background-color: transparent;"
            "    border: 1px solid #30b9bf;"
            "    color: #30b9bf;"
            "    border-radius: 16px;"
            "    padding: 6px 16px;"
            "    font-size: 9pt;"
            "    font-weight: 600;"
            "}"
            ""
            "#secondaryButton:hover {"
            "    background-color: #30b9bf;"
            "    color: white;"
            "}"
            ""
            "#secondaryButton:pressed {"
            "    background-color: #26a0a6;"
            "    color: white;"
            "}"
            ""
            "/* Default QPushButton */"
            "QPushButton {"
            "    background-color: #e2efff;"
            "    color: #1e40af;"
            "    border: 1px solid #bfdbfe;"
            "    border-radius: 8px;"
            "    padding: 8px 16px;"
            "    font-size: 10pt;"
            "}"
            ""
            "QPushButton:hover {"
            "    background-color: #dbeafe;"
            "    border-color: #93c5fd;"
            "}"
            ""
            "QPushButton:pressed {"
            "    background-color: #bfdbfe;"
            "    border-color: #60a5fa;"
            "}"
            ""
            "/* ALL QLabel */"
            "QLabel {"
            "    color: #1f2937;"
            "    background-color: transparent;"
            "}"
            ""
            "#sidebar QLabel {"
            "    color: #1f2937;"
            "}"
            ""
            "/* Status Badges */"
            ".statusAccepted {"
            "    background-color: #dcfce7;"
            "    color: #166534;"
            "    border: 1px solid #86efac;"
            "    border-radius: 12px;"
            "    padding: 4px 12px;"
            "    font-size: 9pt;"
            "    font-weight: bold;"
            "}"
            ""
            ".statusReview {"
            "    background-color: #fef3c7;"
            "    color: #92400e;"
            "    border: 1px solid #fcd34d;"
            "    border-radius: 12px;"
            "    padding: 4px 12px;"
            "    font-size: 9pt;"
            "    font-weight: bold;"
            "}"
            ""
            ".statusRejected {"
            "    background-color: #fee2e2;"
            "    color: #991b1b;"
            "    border: 1px solid #fca5a5;"
            "    border-radius: 12px;"
            "    padding: 4px 12px;"
            "    font-size: 9pt;"
            "    font-weight: bold;"
            "}"
            ""
            "/* Scrollbars */"
            "QScrollBar:vertical {"
            "    background: #f6f8fc;"
            "    width: 10px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:vertical {"
            "    background: #c0d0e8;"
            "    min-height: 30px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:vertical:hover {"
            "    background: #30b9bf;"
            "}"
            ""
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
            "    height: 0px;"
            "}"
            ""
            "QScrollBar:horizontal {"
            "    background: #f6f8fc;"
            "    height: 10px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:horizontal {"
            "    background: #c0d0e8;"
            "    min-width: 30px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:horizontal:hover {"
            "    background: #30b9bf;"
            "}"
            ""
            "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {"
            "    width: 0px;"
            "}"
            ""
            "/* ALL Input Fields */"
            "QLineEdit {"
            "    background-color: #ffffff !important;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1f2937;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "}"
            ""
            "QLineEdit:focus {"
            "    border: 2px solid #30b9bf;"
            "}"
            ""
            "QLineEdit:hover {"
            "    border: 1px solid #30b9bf;"
            "}"
            ""
            "QTextEdit, QPlainTextEdit {"
            "    background-color: #ffffff !important;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1f2937;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "}"
            ""
            "QTextEdit:focus, QPlainTextEdit:focus {"
            "    border: 2px solid #30b9bf;"
            "}"
            ""
            "QTextEdit:hover, QPlainTextEdit:hover {"
            "    border: 1px solid #30b9bf;"
            "}"
            ""
            "/* Combo Boxes */"
            "QComboBox {"
            "    background-color: #ffffff !important;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1f2937;"
            "    min-width: 100px;"
            "}"
            ""
            "QComboBox:hover {"
            "    border: 1px solid #30b9bf;"
            "}"
            ""
            "QComboBox:focus {"
            "    border: 2px solid #30b9bf;"
            "}"
            ""
            "QComboBox::drop-down {"
            "    border: none;"
            "    width: 20px;"
            "}"
            ""
            "QComboBox::down-arrow {"
            "    width: 0;"
            "    height: 0;"
            "    border-left: 5px solid transparent;"
            "    border-right: 5px solid transparent;"
            "    border-top: 5px solid #6b7280;"
            "}"
            ""
            "QComboBox QAbstractItemView {"
            "    background-color: #ffffff;"
            "    border: 1px solid #c0d0e8;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "    outline: none;"
            "}"
            ""
            "/* Checkboxes & Radio */"
            "QCheckBox, QRadioButton {"
            "    spacing: 8px;"
            "    color: #1f2937;"
            "}"
            ""
            "QCheckBox::indicator, QRadioButton::indicator {"
            "    width: 18px;"
            "    height: 18px;"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 4px;"
            "    background-color: #ffffff;"
            "}"
            ""
            "QCheckBox::indicator:checked {"
            "    background-color: #30b9bf;"
            "    border: 1px solid #30b9bf;"
            "}"
            ""
            "QRadioButton::indicator {"
            "    border-radius: 10px;"
            "}"
            ""
            "QRadioButton::indicator:checked {"
            "    background-color: #ffffff;"
            "    border: 5px solid #30b9bf;"
            "}"
            ""
            "QCheckBox::indicator:hover, QRadioButton::indicator:hover {"
            "    border: 1px solid #30b9bf;"
            "}"
            ""
            "/* Progress Bar */"
            "QProgressBar {"
            "    border: 1px solid #c0d0e8;"
            "    border-radius: 6px;"
            "    text-align: center;"
            "    background-color: #f1f5f9;"
            "    color: #1f2937;"
            "    font-weight: bold;"
            "}"
            ""
            "QProgressBar::chunk {"
            "    background-color: #30b9bf;"
            "    border-radius: 4px;"
            "}"
            ""
            "/* Tooltips */"
            "QToolTip {"
            "    background-color: #1e293b;"
            "    color: #f1f5f9;"
            "    border: 1px solid #30b9bf;"
            "    padding: 6px 8px;"
            "    border-radius: 4px;"
            "}"
            ""
            "/* Tables / List / Tree */"
            "QTableView, QListView, QTreeView {"
            "    background-color: #ffffff;"
            "    border: 1px solid #e2e8f0;"
            "    border-radius: 8px;"
            "    gridline-color: #e2e8f0;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "    color: #1f2937;"
            "    outline: none;"
            "}"
            ""
            "QTableView::item:hover, QListView::item:hover, QTreeView::item:hover {"
            "    background-color: #f0f9ff;"
            "}"
            ""
            "QHeaderView::section {"
            "    background-color: #f1f5f9;"
            "    padding: 8px;"
            "    border: none;"
            "    border-right: 1px solid #e2e8f0;"
            "    border-bottom: 1px solid #e2e8f0;"
            "    color: #1f2937;"
            "    font-weight: bold;"
            "    font-size: 9pt;"
            "}"
            ""
            "/* Menu Bar */"
            "QMenuBar {"
            "    background-color: #ffffff;"
            "    border-bottom: 1px solid #d8e0f0;"
            "    color: #1f2937;"
            "}"
            ""
            "QMenuBar::item:selected {"
            "    background-color: #e2efff;"
            "}"
            ""
            "QMenu {"
            "    background-color: #ffffff;"
            "    border: 1px solid #d8e0f0;"
            "    color: #1f2937;"
            "}"
            ""
            "QMenu::item:selected {"
            "    background-color: #30b9bf;"
            "    color: white;"
            "}"
            ""
            "/* Status Bar */"
            "QStatusBar {"
            "    background-color: #f1f5f9;"
            "    border-top: 1px solid #d8e0f0;"
            "    color: #4b5563;"
            "}"
            ""
            "/* Group Box */"
            "QGroupBox {"
            "    border: 1px solid #d8e0f0;"
            "    border-radius: 8px;"
            "    margin-top: 12px;"
            "    padding-top: 12px;"
            "    color: #1f2937;"
            "    font-weight: bold;"
            "}"
            ""
            "QGroupBox::title {"
            "    subcontrol-origin: margin;"
            "    subcontrol-position: top left;"
            "    padding: 0 8px;"
            "    color: #1a7a7f;"
            "}"
            ""
            "/* Tabs */"
            "QTabWidget::pane {"
            "    border: 1px solid #d8e0f0;"
            "    background-color: #ffffff;"
            "    border-radius: 8px;"
            "}"
            ""
            "QTabBar::tab {"
            "    background-color: #f8fafc;"
            "    color: #64748b;"
            "    border: none;"
            "    border-bottom: 3px solid transparent;"
            "    padding: 12px 20px;"
            "    font-weight: 500;"
            "}"
            ""
            "QTabBar::tab:selected {"
            "    color: #1f2937;"
            "    background-color: #ffffff;"
            "    border-bottom: 3px solid #30b9bf;"
            "}"
            ""
            "QTabBar::tab:hover {"
            "    color: #1f2937;"
            "    background-color: #f1f5f9;"
            "}"
            );} else{
        this->setStyleSheet(
            "/* Research Publication App Stylesheet - PREMIUM MUTED DARK */"
            ""
            "* {"
            "    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Arial, sans-serif;"
            "}"
            ""
            "QMainWindow {"
            "    background-color: #2a3142;"
            "}"
            ""
            "#sidebar {"
            "    background-color: #343d52;"
            "    border-right: 1px solid #1f2530;"
            "}"
            ""
            "/* For QDateEdit */"
            "QDateEdit {"
            "    background-color: #d4dce8 !important;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1a1f2e;"
            "}"
            ""
            "/* For QSpinBox / QDoubleSpinBox */"
            "QSpinBox, QDoubleSpinBox {"
            "    background-color: #d4dce8 !important;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1a1f2e;"
            "}"
            ""
            "#appTitle {"
            "    color: #1a1f2e;"
            "    font-size: 20pt;"
            "    font-weight: bold;"
            "    padding: 16px;"
            "    background-color: transparent;"
            "}"
            ""
            "/* Navigation Buttons */"
            "#homeNavButton, #myPageNavButton, #quitb {"
            "    text-align: left;"
            "    padding: 12px 16px;"
            "    border-radius: 8px;"
            "    background-color: transparent;"
            "    color: #0d1117;"
            "    font-size: 11pt;"
            "    border: none;"
            "}"
            ""
            "#homeNavButton:hover, #myPageNavButton:hover {"
            "    background-color: rgba(48, 185, 191, 0.2);"
            "}"
            ""
            "#homeNavButton:pressed, #myPageNavButton:pressed {"
            "    background-color: rgba(48, 185, 191, 0.3);"
            "}"
            ""
            "#quitb {"
            "    color: #0d1117;"
            "    margin-top: 8px;"
            "}"
            ""
            "#quitb:hover {"
            "    background-color: rgba(220, 38, 38, 0.2);"
            "    color: #b91c1c;"
            "}"
            ""
            "/* Top Bars */"
            "#homeTopBar, #myPageTopBar {"
            "    background-color: #2a3142;"
            "    padding: 16px 24px;"
            "}"
            ""
            "#homeTitle, #myPageTitle {"
            "    color: #0d1117;"
            "    font-size: 18pt;"
            "    font-weight: bold;"
            "    background-color: transparent;"
            "}"
            ""
            "/* Search Bar */"
            "QLineEdit#searchBar {"
            "    background-color: #d4dce8 !important;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 20px;"
            "    padding: 10px 16px;"
            "    color: #1a1f2e;"
            "    font-size: 10pt;"
            "}"
            ""
            "QLineEdit#searchBar:focus {"
            "    border: 2px solid #30b9bf;"
            "    background-color: #e0e7f1 !important;"
            "}"
            ""
            "QLineEdit#searchBar:hover {"
            "    border: 1px solid #30b9bf;"
            "    background-color: #dce4f0 !important;"
            "}"
            ""
            "/* Scroll Areas */"
            "#homeScrollArea, #myScrollArea {"
            "    background-color: #2a3142;"
            "    border: none;"
            "}"
            ""
            "#homeScrollArea > QWidget, #myScrollArea > QWidget {"
            "    background-color: #2a3142;"
            "}"
            ""
            "/* Publication Cards */"
            "#publicationCard {"
            "    background-color: #c5d0e2;"
            "    border-radius: 10px;"
            "    border: 1px solid #a8b5c9;"
            "}"
            ""
            "#publicationCard:hover {"
            "    border: 1px solid #30b9bf;"
            "    background-color: #d0dae9;"
            "    box-shadow: 0 4px 12px rgba(48, 185, 191, 0.15);"
            "}"
            ""
            "#cardTitle {"
            "    color: #0d1117;"
            "    font-size: 14pt;"
            "    font-weight: bold;"
            "    background-color: transparent;"
            "}"
            ""
            "#cardAuthors {"
            "    color: #2d3748;"
            "    font-size: 10pt;"
            "    background-color: transparent;"
            "}"
            ""
            "#cardDate {"
            "    color: #4a5568;"
            "    font-size: 9pt;"
            "    background-color: transparent;"
            "}"
            ""
            "/* Primary Button (Upload/Browse) */"
            "#Browse {"
            "    background-color: #30b9bf;"
            "    color: white;"
            "    border: none;"
            "    border-radius: 20px;"
            "    padding: 10px 20px;"
            "    font-weight: bold;"
            "    font-size: 10pt;"
            "}"
            ""
            "#Browse:hover {"
            "    background-color: #3dd4db;"
            "}"
            ""
            "#Browse:pressed {"
            "    background-color: #26a0a6;"
            "}"
            ""
            "/* Secondary Buttons (View, Download) */"
            "#secondaryButton {"
            "    background-color: transparent;"
            "    border: 1px solid #30b9bf;"
            "    color: #0c7a7f;"
            "    border-radius: 16px;"
            "    padding: 6px 16px;"
            "    font-size: 9pt;"
            "    font-weight: 600;"
            "}"
            ""
            "#secondaryButton:hover {"
            "    background-color: #30b9bf;"
            "    color: white;"
            "}"
            ""
            "#secondaryButton:pressed {"
            "    background-color: #26a0a6;"
            "    color: white;"
            "}"
            ""
            "/* Default QPushButton */"
            "QPushButton {"
            "    background-color: #b8c5d9;"
            "    color: #0d1117;"
            "    border: 1px solid #98a8c0;"
            "    border-radius: 8px;"
            "    padding: 8px 16px;"
            "    font-size: 10pt;"
            "    font-weight: 500;"
            "}"
            ""
            "QPushButton:hover {"
            "    background-color: #c8d4e5;"
            "    border-color: #a8b5c9;"
            "}"
            ""
            "QPushButton:pressed {"
            "    background-color: #a8b5c9;"
            "    border-color: #8898b0;"
            "}"
            ""
            "/* ALL QLabel */"
            "QLabel {"
            "    color: #0d1117;"
            "    background-color: transparent;"
            "}"
            ""
            "#sidebar QLabel {"
            "    color: #1a1f2e;"
            "}"
            ""
            "/* Status Badges */"
            ".statusAccepted {"
            "    background-color: #a7f3d0;"
            "    color: #064e3b;"
            "    border: 1px solid #6ee7b7;"
            "    border-radius: 12px;"
            "    padding: 4px 12px;"
            "    font-size: 9pt;"
            "    font-weight: bold;"
            "}"
            ""
            ".statusReview {"
            "    background-color: #fde68a;"
            "    color: #78350f;"
            "    border: 1px solid #fcd34d;"
            "    border-radius: 12px;"
            "    padding: 4px 12px;"
            "    font-size: 9pt;"
            "    font-weight: bold;"
            "}"
            ""
            ".statusRejected {"
            "    background-color: #fecaca;"
            "    color: #7f1d1d;"
            "    border: 1px solid #fca5a5;"
            "    border-radius: 12px;"
            "    padding: 4px 12px;"
            "    font-size: 9pt;"
            "    font-weight: bold;"
            "}"
            ""
            "/* Scrollbars */"
            "QScrollBar:vertical {"
            "    background: #2a3142;"
            "    width: 10px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:vertical {"
            "    background: #545e73;"
            "    min-height: 30px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:vertical:hover {"
            "    background: #30b9bf;"
            "}"
            ""
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {"
            "    height: 0px;"
            "}"
            ""
            "QScrollBar:horizontal {"
            "    background: #2a3142;"
            "    height: 10px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:horizontal {"
            "    background: #545e73;"
            "    min-width: 30px;"
            "    border-radius: 5px;"
            "}"
            ""
            "QScrollBar::handle:horizontal:hover {"
            "    background: #30b9bf;"
            "}"
            ""
            "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {"
            "    width: 0px;"
            "}"
            ""
            "/* ALL Input Fields */"
            "QLineEdit {"
            "    background-color: #d4dce8 !important;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1a1f2e;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "}"
            ""
            "QLineEdit:focus {"
            "    border: 2px solid #30b9bf;"
            "    background-color: #e0e7f1 !important;"
            "}"
            ""
            "QLineEdit:hover {"
            "    border: 1px solid #30b9bf;"
            "    background-color: #dce4f0 !important;"
            "}"
            ""
            "QTextEdit, QPlainTextEdit {"
            "    background-color: #d4dce8 !important;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1a1f2e;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "}"
            ""
            "QTextEdit:focus, QPlainTextEdit:focus {"
            "    border: 2px solid #30b9bf;"
            "    background-color: #e0e7f1 !important;"
            "}"
            ""
            "QTextEdit:hover, QPlainTextEdit:hover {"
            "    border: 1px solid #30b9bf;"
            "    background-color: #dce4f0 !important;"
            "}"
            ""
            "/* Combo Boxes */"
            "QComboBox {"
            "    background-color: #d4dce8 !important;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 6px;"
            "    padding: 8px 12px;"
            "    color: #1a1f2e;"
            "    min-width: 100px;"
            "}"
            ""
            "QComboBox:hover {"
            "    border: 1px solid #30b9bf;"
            "    background-color: #dce4f0 !important;"
            "}"
            ""
            "QComboBox:focus {"
            "    border: 2px solid #30b9bf;"
            "    background-color: #e0e7f1 !important;"
            "}"
            ""
            "QComboBox::drop-down {"
            "    border: none;"
            "    width: 20px;"
            "}"
            ""
            "QComboBox::down-arrow {"
            "    width: 0;"
            "    height: 0;"
            "    border-left: 5px solid transparent;"
            "    border-right: 5px solid transparent;"
            "    border-top: 5px solid #2d3748;"
            "}"
            ""
            "QComboBox QAbstractItemView {"
            "    background-color: #d4dce8;"
            "    border: 1px solid #a8b5c9;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "    outline: none;"
            "    color: #1a1f2e;"
            "}"
            ""
            "/* Checkboxes & Radio */"
            "QCheckBox, QRadioButton {"
            "    spacing: 8px;"
            "    color: #0d1117;"
            "}"
            ""
            "QCheckBox::indicator, QRadioButton::indicator {"
            "    width: 18px;"
            "    height: 18px;"
            "    border: 2px solid #6b7a91;"
            "    border-radius: 4px;"
            "    background-color: #d4dce8;"
            "}"
            ""
            "QCheckBox::indicator:checked {"
            "    background-color: #30b9bf;"
            "    border: 2px solid #30b9bf;"
            "}"
            ""
            "QRadioButton::indicator {"
            "    border-radius: 10px;"
            "}"
            ""
            "QRadioButton::indicator:checked {"
            "    background-color: #d4dce8;"
            "    border: 5px solid #30b9bf;"
            "}"
            ""
            "QCheckBox::indicator:hover, QRadioButton::indicator:hover {"
            "    border: 2px solid #30b9bf;"
            "}"
            ""
            "/* Progress Bar */"
            "QProgressBar {"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 6px;"
            "    text-align: center;"
            "    background-color: #c5d0e2;"
            "    color: #0d1117;"
            "    font-weight: bold;"
            "}"
            ""
            "QProgressBar::chunk {"
            "    background-color: #30b9bf;"
            "    border-radius: 4px;"
            "}"
            ""
            "/* Tooltips */"
            "QToolTip {"
            "    background-color: #1a1f2e;"
            "    color: #e0e7f1;"
            "    border: 1px solid #30b9bf;"
            "    padding: 6px 8px;"
            "    border-radius: 4px;"
            "}"
            ""
            "/* Tables / List / Tree */"
            "QTableView, QListView, QTreeView {"
            "    background-color: #c5d0e2;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 8px;"
            "    gridline-color: #98a8c0;"
            "    selection-background-color: #30b9bf;"
            "    selection-color: white;"
            "    color: #0d1117;"
            "    outline: none;"
            "}"
            ""
            "QTableView::item:hover, QListView::item:hover, QTreeView::item:hover {"
            "    background-color: #d0dae9;"
            "}"
            ""
            "QHeaderView::section {"
            "    background-color: #b8c5d9;"
            "    padding: 8px;"
            "    border: none;"
            "    border-right: 1px solid #98a8c0;"
            "    border-bottom: 1px solid #98a8c0;"
            "    color: #0d1117;"
            "    font-weight: bold;"
            "    font-size: 9pt;"
            "}"
            ""
            "/* Menu Bar */"
            "QMenuBar {"
            "    background-color: #343d52;"
            "    border-bottom: 1px solid #1f2530;"
            "    color: #0d1117;"
            "}"
            ""
            "QMenuBar::item:selected {"
            "    background-color: #3e4859;"
            "}"
            ""
            "QMenu {"
            "    background-color: #c5d0e2;"
            "    border: 1px solid #a8b5c9;"
            "    color: #0d1117;"
            "}"
            ""
            "QMenu::item:selected {"
            "    background-color: #30b9bf;"
            "    color: white;"
            "}"
            ""
            "/* Status Bar */"
            "QStatusBar {"
            "    background-color: #343d52;"
            "    border-top: 1px solid #1f2530;"
            "    color: #2d3748;"
            "}"
            ""
            "/* Group Box */"
            "QGroupBox {"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 8px;"
            "    margin-top: 12px;"
            "    padding-top: 12px;"
            "    color: #0d1117;"
            "    font-weight: bold;"
            "}"
            ""
            "QGroupBox::title {"
            "    subcontrol-origin: margin;"
            "    subcontrol-position: top left;"
            "    padding: 0 8px;"
            "    color: #0a5a5f;"
            "}"
            ""
            "/* Tabs */"
            "QTabWidget::pane {"
            "    border: 1px solid #a8b5c9;"
            "    background-color: #c5d0e2;"
            "    border-radius: 8px;"
            "}"
            ""
            "QTabBar::tab {"
            "    background-color: #343d52;"
            "    color: #4a5568;"
            "    border: none;"
            "    border-bottom: 3px solid transparent;"
            "    padding: 12px 20px;"
            "    font-weight: 500;"
            "}"
            ""
            "QTabBar::tab:selected {"
            "    color: #0d1117;"
            "    background-color: #c5d0e2;"
            "    border-bottom: 3px solid #30b9bf;"
            "}"
            "/* Group Box */"
            "QGroupBox {"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 8px;"
            "    margin-top: 12px;"
            "    padding-top: 12px;"
            "    color: #0d1117;"
            "    font-weight: bold;"
            "}"
            ""
            "QGroupBox::title {"
            "    subcontrol-origin: margin;"
            "    subcontrol-position: top left;"
            "    padding: 0 8px;"
            "    color: #0a5a5f;"
            "}"
            ""
            "/* Specific groupBox styling */"
            "QGroupBox#groupBox {"
            "    background-color: #c5d0e2;"
            "    border: 1px solid #a8b5c9;"
            "    border-radius: 8px;"
            "    margin-top: 12px;"
            "    padding: 16px;"
            "    color: #0d1117;"
            "    font-weight: bold;"
            "}"
            ""
            "QGroupBox#groupBox::title {"
            "    subcontrol-origin: margin;"
            "    subcontrol-position: top left;"
            "    padding: 0 8px;"
            "    background-color: transparent;"
            "    color: #0a5a5f;"
            "}"
            ""
            "QTabBar::tab:hover {"
            "    color: #1a1f2e;"
            "    background-color: #545e73;"
            "}"
            );
    }
}
